Repository tenstorrent/tt-mlir, pull requests merged in 2024-12, with the labels that each got.

#1439 Uplift third_party/tt-metal to ab3dc0c4f5c3ce9722261c878970bfa92a212fc9 2024-12-02
  runtime/lib/ttmetal/CMakeLists.txt
  runtime/test/CMakeLists.txt
  third_party/CMakeLists.txt
Labels: uplift

#1463 Uplift third_party/tt-metal to 6a524ab817aeb09c273e37254f39ad8124ddf2f8 2024-12-03
  runtime/include/tt/runtime/detail/ttnn.h
  runtime/lib/ttnn/operations/pool/maxpool2d.cpp
  third_party/CMakeLists.txt
Labels: uplift

#1493 Uplift third_party/tt-metal to dde5614e816b20110b0bb8c96aeefe5a0a7bada1 2024-12-04
  runtime/lib/common/system_desc.cpp
  third_party/CMakeLists.txt
Labels: uplift

#1512 Uplift third_party/tt-metal to 3389120b3747b521fa9b7ef333a379554359d961 2024-12-05
  runtime/lib/ttnn/operations/conv/conv2d.cpp
  runtime/lib/ttnn/operations/pool/maxpool2d.cpp
  third_party/CMakeLists.txt
Labels: uplift

#1522 Uplift third_party/tt-metal to 4952f01a39068cba4e85c93cf34c4f95f10f5c34 2024-12-06
  runtime/tools/python/setup.py
  third_party/CMakeLists.txt
  tools/ttnn-standalone/CMakeLists.txt
Labels: uplift

#1532 Uplift third_party/tt-metal to 10eeea8080971e280fd33ffa0a81d9ec06d49917 2024-12-07
  third_party/CMakeLists.txt
Labels: uplift

#1534 Uplift third_party/tt-metal to 8ee1f823ccc6680fd4ba5aa9004487692da1c545 2024-12-08
  third_party/CMakeLists.txt
Labels: uplift

#1535 Uplift third_party/tt-metal to 7768e89929915f40f7fdb45e352dd4b83f335168 2024-12-09
  third_party/CMakeLists.txt
  tools/ttnn-standalone/CMakeLists.txt
Labels: uplift

#1523 Add pass to create input tensor generator functions for emitc path
  include/ttmlir/Dialect/TTNN/Transforms/Passes.td
  include/ttmlir/Dialect/TTNN/Utils/Utils.h
  lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
  lib/Dialect/TTNN/Transforms/Passes.cpp
  lib/Dialect/TTNN/Utils/Utils.cpp
  test/ttmlir/Dialect/TTNN/Transforms/ttnn_create_input_gens_0.mlir
Labels: EmitC

#1546 Uplift third_party/tt-metal to c2d7b099da7b194475ca7e6cf18c2eff496f866c 2024-12-10
  runtime/lib/common/system_desc.cpp
  runtime/lib/ttmetal/runtime.cpp
  runtime/lib/ttnn/operations/conv/conv2d.cpp
  runtime/lib/ttnn/runtime.cpp
  third_party/CMakeLists.txt
Labels: uplift

#1568 Uplift third_party/tt-metal to 2f59d5e02ef0da955b99cf0f49da1759c772a67a 2024-12-11
  runtime/lib/common/system_desc.cpp
  third_party/CMakeLists.txt
Labels: uplift

#1419 Add EmbeddingBackward op e2e
  include/ttmlir/Conversion/TTIRToTTNN/Utils.h
  include/ttmlir/Dialect/TTIR/IR/TTIROps.td
  include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
  include/ttmlir/Target/TTNN/program.fbs
  lib/Conversion/TTIRToTTIRDecomposition/TTIRToTTIRDecomposition.cpp
  lib/Conversion/TTIRToTTNN/CMakeLists.txt
  lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
  lib/Conversion/TTIRToTTNN/Utils.cpp
  lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
  lib/Dialect/TTIR/IR/TTIROps.cpp
  lib/Dialect/TTNN/IR/TTNNOps.cpp
  lib/Target/TTNN/TTNNToFlatbuffer.cpp
  runtime/lib/ttnn/operations/CMakeLists.txt
  runtime/lib/ttnn/operations/embedding/embedding_backward.cpp
  runtime/lib/ttnn/operations/embedding/embedding_backward.h
  runtime/lib/ttnn/program.cpp
  test/ttmlir/Silicon/TTNN/embedding/embedding_backward.mlir
  tools/ttnn-standalone/ttnn-precompiled.hpp
Labels: MLIR Ops

#1572 Uplift third_party/tt-metal to ed413ee399ad289740105b709c20e9144ec4f035 2024-12-14
  third_party/CMakeLists.txt
Labels: uplift

#1601 Uplift third_party/tt-metal to 6d7cc2c38ae3efc36326f5407698b05fb314b5b0 2024-12-16
  third_party/CMakeLists.txt
Labels: uplift

#1610 Uplift third_party/tt-metal to bbce2c3359e128273a38e2afdcf5e346a0941858 2024-12-17
  runtime/lib/ttnn/operations/creation/empty.cpp
  runtime/lib/ttnn/operations/creation/full.cpp
  runtime/lib/ttnn/runtime.cpp
  third_party/CMakeLists.txt
Labels: uplift

#1627 Uplift third_party/tt-metal to 5d0a53211ef2bfbf5f45b9f632bf360a4519a7d8 2024-12-19
  test/ttmlir/Silicon/TTNN/regression/reshape_5d.mlir
  third_party/CMakeLists.txt
Labels: uplift

#1650 Uplift third_party/tt-metal to 8ab8736293d4213be6dd9e7585a80c2acdcac855 2024-12-20
  test/ttmlir/Silicon/TTNN/regression/unsqueeze.mlir
  third_party/CMakeLists.txt
Labels: uplift

#1655 Uplift third_party/tt-metal to 2a86ff7fdde8561ec6c60f1635937ac2b13e122f 2024-12-27
  test/ttmlir/Silicon/TTNN/kv_cache/update_cache.mlir
  third_party/CMakeLists.txt
Labels: uplift

#1676 Uplift third_party/tt-metal to 34e10c321807d0b24fc3bd9c349a9a67c4e5741c 2024-12-28
  third_party/CMakeLists.txt
Labels: uplift

#1677 Uplift third_party/tt-metal to d0326ed27d1885b7f0c573f4885f4c9d4f0c9676 2024-12-29
  third_party/CMakeLists.txt
Labels: uplift

#1678 Uplift third_party/tt-metal to 6b3b9ece9d10715c3fb2aeffa898338a0c5f9a1a 2024-12-30
  third_party/CMakeLists.txt
Labels: uplift

#1684 Uplift third_party/tt-metal to c4df003d49057066c59a227d7511fca2e9999043 2024-12-31
  third_party/CMakeLists.txt
Labels: uplift
