Repository tenstorrent/tt-mlir, pull requests merged in 2025-08, with the labels that each got.

#4226 Uplift third_party/tt-metal to d78b2f9ae3d33c468d71c99ee5e8ab7f3606c89d 2025-07-31
  lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
  lib/OpModel/TTNN/TTNNOpModel.cpp
  runtime/include/tt/runtime/detail/ttnn/ttnn.h
  runtime/lib/ttnn/operations/data_movement/slice.cpp
  test/python/golden/test_ttir_ops.py
  test/ttmlir/Silicon/TTNN/n150/pooling/max_pool2d.mlir
  test/ttmlir/Silicon/TTNN/n150/pooling/max_pool2d_unsupported.mlir
  test/unittests/OpModel/TTNN/Lib/TestOpModelLib.cpp
  test/unittests/OpModel/TTNN/Op/TestOpModelInterface.cpp
  third_party/CMakeLists.txt
Labels: uplift

#4387 Uplift third_party/tt-metal to e46b29077a1dfb00cd4b57a8ce9e018b059dd84a 2025-08-06
  include/ttmlir/Conversion/TTNNToEmitC/EmitCConversion.h
  include/ttmlir/Dialect/TTNN/Analysis/Conv2dConfigSearchSpace.h
  include/ttmlir/Dialect/TTNN/IR/TTNNOpsAttrs.td
  include/ttmlir/Dialect/TTNN/Pipelines/TTNNPipelines.h
  include/ttmlir/Dialect/TTNN/Utils/PassOverrides.h
  include/ttmlir/Target/TTNN/operations/conv.fbs
  include/ttmlir/Target/Utils/MLIRToFlatbuffer.h
  lib/Dialect/TTNN/Analysis/Conv2dConfigSearchSpace.cpp
  lib/Dialect/TTNN/Analysis/LegalOpConfigAnalysis.cpp
  lib/Dialect/TTNN/IR/TTNNOpsAttrs.cpp
  lib/Dialect/TTNN/Utils/PassOverrides.cpp
  lib/OpModel/TTNN/Conversion.cpp
  lib/OpModel/TTNN/SingletonDeviceContext.cpp
  lib/OpModel/TTNN/TTNNOpModel.cpp
  python/OptimizerOverrides.cpp
  python/TTNNModule.cpp
  runtime/lib/ttnn/operations/conv/prepare_conv2d_bias.cpp
  runtime/lib/ttnn/operations/conv/prepare_conv2d_weights.cpp
  runtime/lib/ttnn/operations/utils/utils.cpp
  test/ttmlir/Dialect/TTNN/fusing/conv2d_activation_fusing_ttnn.mlir
  test/ttmlir/Dialect/TTNN/optimizer/conv2d_config_override.mlir
  test/ttmlir/EmitC/TTNN/conv/conv2d_conv2dconfig.mlir
  test/ttmlir/Silicon/TTNN/n150/perf/test_perf_conv2d_config.mlir
  test/ttmlir/Silicon/TTNN/n150/perf/test_perf_conv_transpose2d_with_conv2d_config.mlir
  test/unittests/OpModel/TTNN/Lib/TestOpModelLib.cpp
  test/unittests/OpModel/TTNN/Op/TestOpModelInterface.cpp
  test/unittests/Optimizer/TestOptimizerOverrides.cpp
  third_party/CMakeLists.txt
  tools/explorer/tt_adapter/src/tt_adapter/main.py
  tools/explorer/tt_adapter/src/tt_adapter/mlir.py
  tools/tt-alchemist/templates/cpp/local/CMakeLists.txt
  tools/ttnn-standalone/CMakeLists.txt
Labels: uplift

#4406 [TTNNWorkaround] SortOp indices
  include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
  include/ttmlir/Dialect/TTNN/IR/TTNNWorkaroundsPass.h
  lib/Dialect/TTNN/IR/TTNNOps.cpp
  lib/Dialect/TTNN/IR/TTNNWorkaroundsPass.cpp
  test/ttmlir/Dialect/TTNN/Transforms/Workarounds/sort_workaround.mlir
  test/ttmlir/Dialect/TTNN/sort/sort_tests_negative.mlir
Labels: workaround

#4433 Uplift third_party/tt-metal to 28a524e2c1c53c986b0c31884ba9d168a5021f7d 2025-08-12
  test/unittests/OpModel/TTNN/Lib/TestOpModelLib.cpp
  third_party/CMakeLists.txt
Labels: uplift

#4470 Uplift third_party/tt-metal to 3250801aecf626ebd03f8a3d0be94a97b121adaf 2025-08-14
  third_party/CMakeLists.txt
Labels: uplift

#4501 Uplift third_party/tt-metal to 98c764028d2001d60f66eabcb0311c248bc7006b 2025-08-15
  third_party/CMakeLists.txt
Labels: uplift

#4585 Uplift third_party/tt-metal to 795135f0c9fde96c4fed761e274cf8d5ca053247 2025-08-21
  third_party/CMakeLists.txt
  tools/tt-alchemist/csrc/InstallComponents.cmake
Labels: uplift

#4647 [Optimizer] Add constraint API for RandOp
  include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
  include/ttmlir/OpModel/TTNN/MetalHeaders.h
  include/ttmlir/OpModel/TTNN/TTNNOpModel.h
  lib/Dialect/TTNN/IR/TTNNOpModelInterface.cpp
  lib/OpModel/TTNN/TTNNOpModel.cpp
  test/unittests/OpModel/TTNN/Lib/TestOpModelLib.cpp
  test/unittests/OpModel/TTNN/Op/TestOpModelInterface.cpp
Labels: ttnn constraints

#4609 Uplift third_party/tt-metal to 0a04f84fe37cbc584cd679500999d0fb99d1be61 2025-08-22
  include/ttmlir/Dialect/TTNN/Transforms/Workarounds/Decomposition/AllGatherOpRewritePattern.h
  lib/Dialect/TTNN/Transforms/CMakeLists.txt
  lib/Dialect/TTNN/Transforms/Workarounds/Decomposition/AllGatherOpRewritePattern.cpp
  lib/Dialect/TTNN/Transforms/Workarounds/TTNNWorkaroundsPatterns.cpp
  runtime/lib/ttnn/operations/ccl/all_gather.cpp
  runtime/lib/ttnn/operations/ccl/reduce_scatter.cpp
  runtime/tools/ttrt/ttrt/common/run.py
  runtime/tools/ttrt/ttrt/common/util.py
  test/python/golden/test_ttir_llama_1x2_tp.py
  test/python/golden/test_ttir_ops_llmbox.py
  test/python/golden/test_ttir_ops_n300.py
  test/ttmlir/Dialect/TTNN/ccl/all_gather/all_gather_positive.mlir
  test/ttmlir/Dialect/TTNN/ccl/all_reduce/all_reduce_positive.mlir
  test/ttmlir/Silicon/TTNN/n300/ccl/ccl_1x2_all_gather.mlir
  third_party/CMakeLists.txt
  tools/tt-alchemist/templates/cpp/local/ttnn-precompiled.hpp
  tools/tt-alchemist/templates/cpp/standalone/ttnn-precompiled.hpp
  tools/ttnn-standalone/ttnn-precompiled.hpp
Labels: uplift
