Repository tenstorrent/tt-mlir, pull requests merged in 2025-03, with the labels that each got.

#2340 Uplift third_party/tt-metal to f05457a1eb5b45fddbd60b35835439994e06ae9d 2025-02-28
  lib/OpModel/TTNN/CMakeLists.txt
  runtime/lib/ttmetal/CMakeLists.txt
  test/unittests/OpModel/TTNN/Conversion/CMakeLists.txt
  test/unittests/OpModel/TTNN/Lib/CMakeLists.txt
  test/unittests/OpModel/TTNN/Op/CMakeLists.txt
  third_party/CMakeLists.txt
  tools/ttnn-standalone/CMakeLists.txt
Labels: uplift

#2322 Add constraints and runtime API to transpose
  include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
  include/ttmlir/OpModel/TTNN/TTNNOpModel.h
  lib/Dialect/TTNN/IR/TTNNOpModelInterface.cpp
  lib/OpModel/TTNN/MetalHeaders.h
  lib/OpModel/TTNN/TTNNOpModelLib.cpp
  test/unittests/OpModel/TTNN/Lib/TestOpModelLib.cpp
  test/unittests/OpModel/TTNN/Op/TestOpModelInterface.cpp
Labels: TTNN Op Perf Model, TTNN Constraints&L1

#2356 Uplift third_party/tt-metal to bec3eced688f5b154520abed9357aa6440c498db 2025-03-05
  lib/OpModel/TTNN/Conversion.cpp
  lib/OpModel/TTNN/MetalHeaders.h
  runtime/include/tt/runtime/detail/ttmetal.h
  runtime/lib/ttmetal/command_queue.cpp
  runtime/lib/ttnn/operations/include/tt/runtime/ttnn/operations/utils.cpp
  runtime/lib/ttnn/operations/reduction/argmax.cpp
  test/unittests/OpModel/TTNN/Conversion/TestConversion.cpp
  third_party/CMakeLists.txt
Labels: uplift

#2382 Uplift third_party/tt-metal to dff46752a7abdaccd6ce9ef4a9d8e7d078ceddce 2025-03-06
  third_party/CMakeLists.txt
Labels: uplift

#2396 Uplift third_party/tt-metal to 830a442ade6fbe1691e2dfe69f4a3f327327eaec 2025-03-07
  runtime/lib/ttnn/operations/ccl/mesh_shard.cpp
  runtime/lib/ttnn/operations/include/tt/runtime/ttnn/operations/utils.cpp
  third_party/CMakeLists.txt
Labels: uplift

#2380 Add constraints and runtime API to typecast
  include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
  include/ttmlir/OpModel/TTNN/TTNNOpModel.h
  lib/Dialect/TTNN/IR/TTNNOpModelInterface.cpp
  lib/OpModel/TTNN/Conversion.cpp
  lib/OpModel/TTNN/Conversion.hpp
  lib/OpModel/TTNN/MetalHeaders.h
  lib/OpModel/TTNN/TTNNOpModelLib.cpp
  test/unittests/OpModel/TTNN/Lib/TestOpModelLib.cpp
  test/unittests/OpModel/TTNN/Op/TestOpModelInterface.cpp
  test/unittests/OpModel/TTNN/OpModelFixture.h
Labels: TTNN Op Perf Model, TTNN Constraints&L1

#2431 Uplift third_party/tt-metal to 6044ef45b7adfe4999e31fb6c4dcdc55bc1c3377 2025-03-11
  third_party/CMakeLists.txt
Labels: uplift

#2425 Add Constraints and Runtime API for ToLayoutOp
  include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
  include/ttmlir/OpModel/TTNN/TTNNOpModel.h
  lib/Dialect/TTNN/IR/TTNNOpModelInterface.cpp
  lib/OpModel/TTNN/Conversion.cpp
  lib/OpModel/TTNN/Conversion.hpp
  lib/OpModel/TTNN/MetalHeaders.h
  lib/OpModel/TTNN/TTNNOpModelLib.cpp
  test/unittests/OpModel/TTNN/Lib/TestOpModelLib.cpp
  test/unittests/OpModel/TTNN/Op/TestOpModelInterface.cpp
Labels: TTNN Op Perf Model, TTNN Constraints&L1

#2439 Uplift third_party/tt-metal to cd5cf40ccce9dd9e13fa00bc412df22566816edb 2025-03-12
  third_party/CMakeLists.txt
Labels: uplift

#2470 Uplift third_party/tt-metal to bf1298a3e4a3b92dfeae7842f4769826ffa87194 2025-03-13
  lib/Conversion/TTIRToTTIRDecomposition/TTIRToTTIRDecomposition.cpp
  lib/Conversion/TTIRToTTIRDecomposition/TTIRToTTIRDecompositionPass.cpp
  lib/Dialect/TTNN/IR/TTNNOps.cpp
  lib/OpModel/TTNN/MetalHeaders.h
  lib/OpModel/TTNN/SingletonDeviceContext.h
  lib/OpModel/TTNN/TTNNOpModelLib.cpp
  runtime/lib/common/system_desc.cpp
  runtime/lib/ttnn/operations/data_movement/pad.cpp
  runtime/test/ttnn/dylib.cpp
  test/ttmlir/Decomposition/TTIR/arange/arange_tests_positive.mlir
  test/ttmlir/Dialect/TTIR/Decomposition/arange_decomposition.mlir
  third_party/CMakeLists.txt
  tools/ttnn-standalone/CMakeLists.txt
Labels: uplift

#2476 Uplift third_party/tt-metal to 95e4842659459bdf01c7b961706d0c943f2d5e4d 2025-03-14
  runtime/lib/ttmetal/command_queue.cpp
  runtime/lib/ttmetal/runtime.cpp
  third_party/CMakeLists.txt
Labels: uplift

#2486 Uplift third_party/tt-metal to 1d2d6be673f8694bfa95a8afb727b3ae006b3767 2025-03-17
  third_party/CMakeLists.txt
Labels: uplift

#2510 Uplift third_party/tt-metal to 0a5d7803308965f78eada0a572082fdef73e5d01 2025-03-18
  third_party/CMakeLists.txt
Labels: uplift

#2505 Update TTRT docs related to issue (#1730)
  docs/src/adding-an-op.md
  docs/src/ttrt.md
Labels: MLIR Compiler, ttrt

#2541 Uplift third_party/tt-metal to 52d0d874360b7261a9ca65782c1e56e89ae781fb 2025-03-19
  third_party/CMakeLists.txt
Labels: uplift

#2578 Uplift third_party/tt-metal to 5ae0757cba914aef30af1a8629a4b1749cab914a 2025-03-21
  third_party/CMakeLists.txt
Labels: uplift

#2586 Convert Transpose operation between TTIR and Linalg dialects
  lib/Conversion/TTIRToLinalg/TTIRToLinalg.cpp
  test/ttmlir/Conversion/TTIRToLinalg/transpose.mlir
Labels: community

#2653 Uplift third_party/tt-metal to 501c655f49707b4039e8db6c4e9680de0a3db827 2025-03-26
  third_party/CMakeLists.txt
Labels: uplift

#2671 Uplift third_party/tt-metal to 8245606cbc6a6fba60a1f43f02a34212ba2454e8 2025-03-27
  third_party/CMakeLists.txt
Labels: uplift

#2697 Uplift third_party/tt-metal to fc292ceb0c2325ca3f3653e9fa19e3587607cec6 2025-03-28
  third_party/CMakeLists.txt
Labels: uplift

#2727 Uplift third_party/tt-metal to 3407c8fd749afee4ec15c2d44dbb2bf3036ee278 2025-03-31
  third_party/CMakeLists.txt
Labels: uplift
