Repository tenstorrent/tt-mlir, pull requests merged in 2025-02, with the labels that each got.

#2060 Uplift third_party/tt-metal to f8fe02d9f591f4c7f929131630ce5147cfe88f8e 2025-02-01
  include/ttmlir/Conversion/TTNNToEmitC/Utils.h
  lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
  lib/Conversion/TTNNToEmitC/Utils.cpp
  lib/OpModel/TTNN/Conversion.cpp
  lib/OpModel/TTNN/Conversion.hpp
  runtime/lib/ttnn/operations/ccl/mesh_shard.cpp
  runtime/lib/ttnn/operations/creation/empty.cpp
  runtime/lib/ttnn/operations/creation/full.cpp
  runtime/lib/ttnn/operations/creation/ones.cpp
  runtime/lib/ttnn/operations/data_movement/repeat.cpp
  runtime/lib/ttnn/operations/pool/maxpool2d.cpp
  runtime/lib/ttnn/runtime.cpp
  runtime/test/include/tt/runtime/ttnn/test/dylib.cpp
  test/unittests/OpModel/TTNN/Conversion/TestConversion.cpp
  third_party/CMakeLists.txt
  tools/ttnn-standalone/ttnn-standalone.cpp
Labels: uplift

#2062 Uplift third_party/tt-metal to 2e804030c40753c4420a12cbce8ad4639bb50ac8 2025-02-02
  third_party/CMakeLists.txt
Labels: uplift

#2071 Uplift third_party/tt-metal to be19f2d17d56b7ea5267deda107baaad42829888 2025-02-03
  third_party/CMakeLists.txt
Labels: uplift

#2074 Add improvements to Adding-an-op docs, specifically emitc sections
  docs/src/adding-an-op.md
  lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
  tools/ttnn-standalone/ttnn-precompiled.hpp
Labels: EmitC

#2093 Uplift third_party/tt-metal to 8d9efbfbab99a03f71ca69681606a6c3c05a67ea 2025-02-04
  third_party/CMakeLists.txt
Labels: uplift

#2099 [skip ci] Skip build and test if PR is draft
  .github/workflows/on-pr.yml
Labels: enhancement, CI / Infra

#2109 Uplift third_party/tt-metal to b981271938b34827a53a9f74a49be9a0c3388eed 2025-02-05
  runtime/lib/ttnn/operations/context/get_device.cpp
  third_party/CMakeLists.txt
Labels: uplift

#2128 Uplift third_party/tt-metal to b093594aa5fc01f7c008a0b5ffddbcf2713bd8f7 2025-02-06
  lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
  third_party/CMakeLists.txt
  tools/ttnn-standalone/CMakeLists.txt
Labels: uplift

#2139 Uplift third_party/tt-metal to b552fb8ae14236777983e3521a312dd78432f0e1 2025-02-07
  lib/OpModel/TTNN/Conversion.cpp
  lib/OpModel/TTNN/MetalHeaders.h
  runtime/lib/ttnn/runtime.cpp
  third_party/CMakeLists.txt
  tools/ttnn-standalone/ttnn-precompiled.hpp
Labels: uplift

#2155 Uplift third_party/tt-metal to 38578b33849c41ad70f5375856d736bc77239b8c 2025-02-10
  runtime/lib/ttnn/operations/data_movement/pad.cpp
  runtime/lib/ttnn/operations/pool/maxpool2d.cpp
  third_party/CMakeLists.txt
  tools/ttnn-standalone/CMakeLists.txt
Labels: uplift

#2172 Uplift third_party/tt-metal to 02fb2125f3fe1f05afd38bcea7993ccb7df87313 2025-02-11
  test/ttmlir/Silicon/TTNN/n150/perf/test_perf_conv_transpose2d.mlir
  test/ttmlir/Silicon/TTNN/n150/simple_conv_transpose2d.mlir
  third_party/CMakeLists.txt
Labels: uplift

#2179 Uplift third_party/tt-metal to d221ac28c4ed0d25616f5e6aeff50c12b9b9592b 2025-02-12
  third_party/CMakeLists.txt
Labels: uplift

#2183 Uplift third_party/tt-metal to 7fe2764ae519084817342949a1307cf163d030f4 2025-02-13
  third_party/CMakeLists.txt
Labels: uplift

#2186 Uplift third_party/tt-metal to 941b34cff33ce2953cf984ec8898af25dbfbfbb3 2025-02-14
  third_party/CMakeLists.txt
Labels: uplift

#2144 Add llama and resnet emitc tests
  include/ttmlir/Dialect/TTNN/Utils/TransformUtils.h
  lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
  lib/Dialect/TTNN/Transforms/Passes.cpp
  lib/Dialect/TTNN/Utils/TransformUtils.cpp
  test/ttmlir/EmitC/TTNN/models/llama_prefill.mlir
  test/ttmlir/EmitC/TTNN/models/resnet.mlir
  test/ttmlir/EmitC/TTNN/tensor/repeat_interleave.mlir
  tools/ttnn-standalone/ci_compile_dylib.py
  tools/ttnn-standalone/ttnn-precompiled.hpp
Labels: EmitC

#2208 Uplift third_party/tt-metal to 3200cb91afaaa05b33d7f23db424912ac370cfbb 2025-02-19
  runtime/lib/ttnn/include/tt/runtime/ttnn/types.h
  runtime/lib/ttnn/operations/creation/empty.cpp
  runtime/lib/ttnn/operations/creation/full.cpp
  runtime/lib/ttnn/runtime.cpp
  runtime/lib/ttnn/types/types.cpp
  third_party/CMakeLists.txt
Labels: uplift

#2239 Uplift third_party/tt-metal to 99e8f45516093967fd56ff3de98efa47868a3a02 2025-02-21
  runtime/lib/common/system_desc.cpp
  runtime/lib/ttmetal/runtime.cpp
  runtime/lib/ttnn/runtime.cpp
  third_party/CMakeLists.txt
Labels: uplift

#2256 Uplift third_party/tt-metal to 57ba436ec4366d9129df6a53b2d9e1e828ef0356 2025-02-25
  runtime/lib/common/system_desc.cpp
  runtime/lib/ttmetal/runtime.cpp
  runtime/lib/ttnn/operations/context/get_device.cpp
  runtime/lib/ttnn/operations/eltwise/binary/binary.cpp
  runtime/lib/ttnn/operations/eltwise/binary/binary_composite.cpp
  runtime/lib/ttnn/operations/include/tt/runtime/ttnn/operations/eltwise/binary/utils.cpp
  runtime/lib/ttnn/operations/include/tt/runtime/ttnn/operations/eltwise/binary/utils.h
  runtime/lib/ttnn/runtime.cpp
  third_party/CMakeLists.txt
Labels: uplift

#2290 Uplift third_party/tt-metal to e0585b2cdb34e013544623d04beb2120209bda8e 2025-02-26
  third_party/CMakeLists.txt
Labels: uplift

#2273 Enable constraints and runtime measurement for Reshape and Mean Ops
  include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
  include/ttmlir/OpModel/TTNN/TTNNOpModel.h
  lib/Dialect/TTNN/IR/TTNNOpModelInterface.cpp
  lib/OpModel/TTNN/Conversion.cpp
  lib/OpModel/TTNN/Conversion.hpp
  lib/OpModel/TTNN/MetalHeaders.h
  lib/OpModel/TTNN/TTNNOpModelLib.cpp
  test/unittests/OpModel/TTNN/Lib/TestOpModelLib.cpp
  test/unittests/OpModel/TTNN/Op/TestOpModelInterface.cpp
Labels: TTNN Op Perf Model, TTNN Constraints&L1

#2307 Uplift third_party/tt-metal to 45186bcf465d6bad3d5e8efaf3ef5afb9e2de2d9 2025-02-27
  third_party/CMakeLists.txt
Labels: uplift

#2327 Uplift third_party/tt-metal to 9b3d8557734bba9b5c7e91e178b85e4e019022cf 2025-02-28
  third_party/CMakeLists.txt
Labels: uplift
