Repository tenstorrent/tt-mlir, pull requests merged in 2025-04, with the labels that each got.

#1056 Added Atan2Op support
  include/ttmlir/Dialect/TTIR/IR/TTIROps.td
  include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
  include/ttmlir/Target/TTNN/program.fbs
  lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp
  lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
  lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
  lib/Target/TTNN/TTNNToFlatbuffer.cpp
  runtime/lib/ttnn/operations/eltwise/binary/binary_composite.cpp
  runtime/lib/ttnn/operations/eltwise/binary/binary_composite.h
  test/ttmlir/Conversion/StableHLOToTTIR/binary/atan2_op.mlir
  test/ttmlir/Dialect/TTNN/eltwise/binary/atan2/simple_atan2.mlir
  test/ttmlir/EmitC/TTNN/eltwise_binary/atan2.mlir
  test/ttmlir/Silicon/TTNN/n150/eltwise/binary/atan2/simple_atan2.mlir
Labels: MLIR Ops

#2766 Uplift third_party/tt-metal to 7598b7ecd1426ae6fe1f54eb532a1dca00efcbf0 2025-04-01
  third_party/CMakeLists.txt
  tools/ttnn-standalone/CMakeLists.txt
Labels: uplift

#2795 Uplift third_party/tt-metal to 4acdb8b52797aa34b6c4bba1f8212deeefa0f68c 2025-04-02
  lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
  runtime/lib/ttnn/operations/eltwise/unary/unary.cpp
  third_party/CMakeLists.txt
Labels: uplift

#2801 Add docker image retention test
  .github/workflows/container-image-retention.yml
Labels: CI / Infra

#2811 Uplift third_party/tt-metal to 636094054d73552b36166a596e4deb79c5756a2f 2025-04-03
  third_party/CMakeLists.txt
Labels: uplift

#2864 Uplift third_party/tt-metal to e2365cefc8aa1a73d58bc3b20a099e76cd8e75e1 2025-04-08
  third_party/CMakeLists.txt
Labels: uplift

#2886 Uplift third_party/tt-metal to 678a464f7f15d3581fae286df0017100882e7975 2025-04-09
  runtime/lib/ttnn/operations/data_movement/pad.cpp
  third_party/CMakeLists.txt
Labels: uplift

#2896 Uplift third_party/tt-metal to c9e4a1ac43c37f0b801788ac6280c25960ad5296 2025-04-10
  runtime/lib/ttnn/operations/data_movement/pad.cpp
  runtime/lib/ttnn/operations/eltwise/binary/binary.cpp
  third_party/CMakeLists.txt
Labels: uplift

#2909 Uplift third_party/tt-metal to ddba2f06d0a120ce4d65ecfad15befd65400e9c7 2025-04-11
  third_party/CMakeLists.txt
Labels: uplift

#2927 Uplift third_party/tt-metal to 4f706555c6cfcb35a6a1f69783333c04e20ce683 2025-04-14
  include/ttmlir/Conversion/TTNNToEmitC/EmitCConversion.h
  lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
  runtime/lib/ttnn/operations/conv/conv2d.cpp
  runtime/lib/ttnn/operations/eltwise/binary/binary_composite.cpp
  runtime/lib/ttnn/operations/eltwise/unary/unary.cpp
  third_party/CMakeLists.txt
Labels: uplift

#2944 Uplift third_party/tt-metal to ea25506219c719e491c8deb100c504a60bd0e392 2025-04-15
  third_party/CMakeLists.txt
Labels: uplift

#2971 Uplift third_party/tt-metal to 70883c9145a607b37adaca05a22e3a9ca2f61368 2025-04-16
  lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
  runtime/lib/ttnn/operations/reduction/argmax.cpp
  third_party/CMakeLists.txt
Labels: uplift

#2980 Uplift third_party/tt-metal to f50d050e2d0ce343b9766a3f8826c1975d0802e3 2025-04-17
  runtime/lib/common/system_desc.cpp
  runtime/lib/ttnn/operations/data_movement/pad.cpp
  third_party/CMakeLists.txt
Labels: uplift

#2997 Changes required to use tt-mlir dialects out-of-tree
  cmake/modules/CMakeLists.txt
  lib/Dialect/TTKernel/IR/CMakeLists.txt
  lib/Dialect/TTMetal/IR/CMakeLists.txt
Labels: community

#2996 Uplift third_party/tt-metal to 5147622f25fc1cdb13f83cca1762b7f623cc2b00 2025-04-21
  lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
  lib/OpModel/TTNN/MetalHeaders.h
  runtime/lib/ttnn/operations/eltwise/binary/binary_composite.cpp
  test/ttmlir/Silicon/TTNN/n150/eltwise/binary/maximum/maximum_broadcast.mlir
  test/ttmlir/Silicon/TTNN/n150/eltwise/binary/minimum/minimum_broadcast.mlir
  test/ttmlir/Silicon/TTNN/n150/eltwise/binary/pow/pow_broadcast.mlir
  test/unittests/OpModel/TTNN/Lib/TestOpModelLib.cpp
  test/unittests/OpModel/TTNN/Op/TestOpModelInterface.cpp
  third_party/CMakeLists.txt
  tools/ttnn-standalone/CMakeLists.txt
Labels: uplift

#3067 Uplift third_party/tt-metal to e75564a41b6f7d4e51229dd2f2953e35c1a636bc 2025-04-23
  third_party/CMakeLists.txt
Labels: uplift

#3068 Uplift third_party/tt-metal to 0d26beb2720e95946d48a6bb9e096e0052f647af 2025-04-24
  third_party/CMakeLists.txt
Labels: uplift
