Repository tenstorrent/tt-mlir, pull requests merged in 2025-01, with the labels that each got.

#1695 Uplift third_party/tt-metal to 0979abdb853ad4cc8a32d90cce6825a3967d1adc 2025-01-01
  third_party/CMakeLists.txt
Labels: uplift

#1696 Uplift third_party/tt-metal to d9304dd4acf235b03a3e8953b70a069802e0704c 2025-01-02
  third_party/CMakeLists.txt
Labels: uplift

#1697 Uplift third_party/tt-metal to c066c3f3d2202c87258ed400307e7f6e26d372a7 2025-01-03
  third_party/CMakeLists.txt
Labels: uplift

#1699 Uplift third_party/tt-metal to fe6a3da9cf5d064a61a4fc626502cf1544446eb9 2025-01-04
  runtime/lib/ttnn/operations/data_movement/permute.cpp
  third_party/CMakeLists.txt
Labels: uplift

#1700 Uplift third_party/tt-metal to aaf2d7304c138c046efd5c0a94c14da3e6f95ce4 2025-01-05
  third_party/CMakeLists.txt
Labels: uplift

#1702 Uplift third_party/tt-metal to cb02e398ca4021496be4b248834995e57aa98a24 2025-01-06
  third_party/CMakeLists.txt
Labels: uplift

#1717 Uplift third_party/tt-metal to e6c029ed92adade7e1d42c4a5468df5a7af1a5b0 2025-01-07
  test/unittests/OpModel/TTNN/Lib/TestOpModelLib.cpp
  third_party/CMakeLists.txt
Labels: uplift

#1731 Uplift third_party/tt-metal to 9c5a0b2e0a0edba747613d2afb3e56dacb5776ac 2025-01-10
  third_party/CMakeLists.txt
Labels: uplift

#1752 Uplift third_party/tt-metal to a6ec1c0a02c3b9dc55e769618639e0439ef9c06b 2025-01-13
  lib/OpModel/TTNN/Conversion.cpp
  runtime/lib/ttnn/include/tt/runtime/ttnn/utils.cpp
  runtime/lib/ttnn/operations/include/tt/runtime/ttnn/operations/utils.cpp
  test/unittests/OpModel/TTNN/Conversion/TestConversion.cpp
  third_party/CMakeLists.txt
Labels: uplift

#1770 Uplift third_party/tt-metal to 0d4d99618a90640bd2a742535bb4f6c8ec6ba164 2025-01-14
  third_party/CMakeLists.txt
Labels: uplift

#1783 Uplift third_party/tt-metal to 5d4c047dacf2606dd56c7b4d51d5049bf2c6846a 2025-01-15
  third_party/CMakeLists.txt
Labels: uplift

#1793 Uplift third_party/tt-metal to 3a9637d52b003d5d5eda455cc72fbeb75a689f32 2025-01-15
  runtime/lib/common/system_desc.cpp
  runtime/lib/ttmetal/runtime.cpp
  runtime/lib/ttnn/runtime.cpp
  third_party/CMakeLists.txt
Labels: uplift

#1853 Uplift third_party/tt-metal to eadc98f1c0f714c423fdfc97689afbc50c0dca3b 2025-01-16
  runtime/lib/ttnn/operations/ccl/mesh_shard.cpp
  third_party/CMakeLists.txt
Labels: uplift

#1875 Uplift third_party/tt-metal to a8396fa5071ea9b0d6754c0317b68871c65d3283 2025-01-17
  lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
  lib/Conversion/TTNNToEmitC/Utils.cpp
  lib/OpModel/TTNN/MetalHeaders.h
  runtime/include/tt/runtime/detail/ttmetal.h
  runtime/include/tt/runtime/detail/ttnn.h
  runtime/lib/common/system_desc.cpp
  runtime/lib/ttnn/operations/creation/empty.cpp
  runtime/lib/ttnn/operations/creation/full.cpp
  runtime/lib/ttnn/operations/creation/ones.cpp
  runtime/lib/ttnn/runtime.cpp
  third_party/CMakeLists.txt
  tools/ttnn-standalone/CMakeLists.txt
  tools/ttnn-standalone/ttnn-dylib.cpp
  tools/ttnn-standalone/ttnn-precompiled.hpp
  tools/ttnn-standalone/ttnn-standalone.cpp
Labels: uplift

#1884 Uplift third_party/tt-metal to 0b35308ff8e1c37d9643b385fe193ac1bc78bf41 2025-01-18
  third_party/CMakeLists.txt
Labels: uplift

#1885 Uplift third_party/tt-metal to eef7b862079a1f5417690b53380412d1aba30440 2025-01-19
  third_party/CMakeLists.txt
Labels: uplift

#1886 Uplift third_party/tt-metal to 8833f73528eb5a606f44c64016ed51f7220352f2 2025-01-20
  third_party/CMakeLists.txt
Labels: uplift

#1913 Uplift third_party/tt-metal to dea22dcd2cf9eaf01f872849b0916b1064721653 2025-01-21
  third_party/CMakeLists.txt
Labels: uplift

#1917 Uplift third_party/tt-metal to 78f2c0b774ab48bf243093d3111717a8c880dc78 2025-01-22
  third_party/CMakeLists.txt
Labels: uplift

#1918 Update docs for EmitC testing
  docs/src/SUMMARY.md
  docs/src/adding-an-op.md
  docs/src/build.md
  docs/src/emitc-testing.md
  docs/src/lit-testing.md
  docs/src/testing.md
  docs/src/tools.md
  docs/src/ttnn-standalone.md
  lib/Dialect/TTNN/Pipelines/TTNNPipelines.cpp
  test/ttmlir/Dialect/TTNN/pipelines/ttir_to_emitc_add.mlir
  test/ttmlir/EmitC/TTNN/matmul/matmul.mlir
  tools/ttnn-standalone/README.md
  tools/ttnn-standalone/ttnn-standalone.cpp
Labels: EmitC

#1935 Uplift third_party/tt-metal to 182c42462cd61515f60a11a46ee84f303ed073ee 2025-01-23
  include/ttmlir/Dialect/TTKernel/IR/TTKernelOps.td
  lib/Conversion/TTIRToTTMetal/TTIRToTTMetal.cpp
  lib/OpModel/TTNN/TTNNOpModelLib.cpp
  runtime/lib/ttnn/runtime.cpp
  third_party/CMakeLists.txt
  tools/ttnn-standalone/CMakeLists.txt
Labels: uplift

#1955 Uplift third_party/tt-metal to 008a38f361a6135423f5c09401934d2219316516 2025-01-24
  runtime/lib/ttnn/runtime.cpp
  third_party/CMakeLists.txt
Labels: uplift

#1996 Uplift third_party/tt-metal to 3430e961a34f7ca91164e7e1a96b86008df68c27 2025-01-28
  third_party/CMakeLists.txt
Labels: uplift

#2009 Uplift third_party/tt-metal to 3adec9c1702bd61f3015d3c659da802fe130be27 2025-01-29
  third_party/CMakeLists.txt
Labels: uplift

#2036 Uplift third_party/tt-metal to 064646adfcb5f0b923a24a633d532552bd43e06d 2025-01-30
  runtime/lib/common/system_desc.cpp
  runtime/lib/ttmetal/runtime.cpp
  runtime/lib/ttnn/runtime.cpp
  third_party/CMakeLists.txt
Labels: uplift

#2023 #2002: Enable Compile Time Op Runtime Estimation
  include/ttmlir/Dialect/TTNN/IR/TTNNOpModelInterface.td
  include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
  include/ttmlir/OpModel/TTNN/TTNNOpModel.h
  lib/Dialect/TTNN/IR/TTNNOpModelInterface.cpp
  lib/OpModel/TTNN/MetalHeaders.h
  lib/OpModel/TTNN/SingletonDeviceContext.cpp
  lib/OpModel/TTNN/SingletonDeviceContext.h
  lib/OpModel/TTNN/TTNNOpModelLib.cpp
  test/unittests/OpModel/TTNN/Lib/TestOpModelLib.cpp
  test/unittests/OpModel/TTNN/Op/TestOpModelInterface.cpp
Labels: TTNN Op Perf Model, TTNN Constraints&L1

#2051 Uplift third_party/tt-metal to 9d69fb143bac50983dff914c5348539d0a7d2021 2025-01-31
  lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
  runtime/lib/ttnn/operations/data_movement/repeat.cpp
  third_party/CMakeLists.txt
Labels: uplift
