Repository tenstorrent/tt-mlir, pull requests merged in 2025-09, with the labels that each got.

#4734 [Optimizer] Add constraint API for memory management ops
  include/ttmlir/Dialect/TTNN/IR/TTNNBase.td
  include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
  include/ttmlir/OpModel/TTNN/MetalHeaders.h
  include/ttmlir/OpModel/TTNN/TTNNOpModel.h
  lib/Dialect/TTNN/IR/TTNNOpModelInterface.cpp
  lib/OpModel/TTNN/TTNNOpModel.cpp
  test/unittests/OpModel/TTNN/Lib/TestOpModelLib.cpp
  test/unittests/OpModel/TTNN/Op/TestOpModelInterface.cpp
Labels: ttnn constraints

#4761 [Optimizer] Add constraint APIs for SliceDynamicOp
  include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
  include/ttmlir/OpModel/TTNN/TTNNOpModel.h
  lib/Dialect/TTNN/IR/TTNNOpModelInterface.cpp
  lib/OpModel/TTNN/TTNNOpModel.cpp
  test/unittests/OpModel/TTNN/Lib/TestOpModelLib.cpp
  test/unittests/OpModel/TTNN/Op/TestOpModelInterface.cpp
Labels: ttnn constraints

#4767 Uplift third_party/tt-metal to 1c6f2b7a835ff8a9ca20d024cbf7e8cba4c53a69 2025-09-03
  lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
  runtime/lib/ttnn/operations/eltwise/unary/unary.cpp
  test/unittests/OpModel/TTNN/Lib/TestOpModelLib.cpp
  test/unittests/OpModel/TTNN/Op/TestOpModelInterface.cpp
  third_party/CMakeLists.txt
Labels: uplift

#4897 Add `unary_bcast_init` and `unary_bcast_tile` ops
  include/ttmlir/Dialect/TTKernel/IR/TTKernelOps.td
  include/ttmlir/Dialect/TTKernel/IR/TTKernelOpsEnums.td
  include/ttmlir/Dialect/TTKernel/IR/TTKernelOpsTypes.td
  lib/Conversion/TTKernelToEmitC/TTKernelToEmitC.cpp
  lib/Target/TTKernel/TTKernelToCpp.cpp
  test/ttmlir/Conversion/TTKernelToEmitC/ttkernel.mlir
Labels: community

#4757 Fix gather op
  lib/Conversion/TTIRToTTIRDecomposition/TTIRToTTIRDecomposition.cpp
  test/python/golden/test_ttir_ops.py
  tools/builder/base/builder_golden.py
  tools/builder/ttir/ttir_builder.py
Labels: community

#4898 Uplift model-explorer to 1df78077c6fec4d41b32ac2622345f0d2378e3e4 2025-09-15
  tools/explorer/CMakeLists.txt
Labels: uplift

#4824 Uplift third_party/tt-metal to eb1ed9fb73db9bffdf6a288e269263b0867800c2 2025-09-10
  .github/workflows/build-and-test.yml
  include/ttmlir/OpModel/TTNN/MetalHeaders.h
  include/ttmlir/Target/TTNN/types.fbs
  lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
  lib/OpModel/TTNN/CMakeLists.txt
  lib/OpModel/TTNN/TTNNOpModel.cpp
  lib/Target/TTNN/TTNNToFlatbuffer.cpp
  runtime/include/tt/runtime/detail/ttnn/operations/utils.h
  runtime/lib/CMakeLists.txt
  runtime/lib/ttnn/operations/CMakeLists.txt
  runtime/lib/ttnn/operations/pool/pool2d.cpp
  runtime/lib/ttnn/operations/utils/utils.cpp
  runtime/lib/ttnn/runtime.cpp
  runtime/test/CMakeLists.txt
  third_party/CMakeLists.txt
  tools/tt-alchemist/csrc/CMakeLists.txt
  tools/ttrt/setup.py
Labels: uplift

#4985 Uplift model-explorer to a8c2343ea437b045c7a4a59cd8c43d94940e484c 2025-09-17
  tools/explorer/CMakeLists.txt
Labels: uplift

#5011 Retry Uplift tt-metal to 449ce3763f54e862f4094230914639406c… 2025-09-15
  include/ttmlir/Conversion/TTNNToEmitC/EmitCConversion.h
  include/ttmlir/Dialect/TTNN/Analysis/Conv2dConfigSearchSpace.h
  include/ttmlir/Dialect/TTNN/Analysis/LegalOpConfigAnalysis.h
  include/ttmlir/Dialect/TTNN/IR/TTNNOpsAttrs.td
  include/ttmlir/Dialect/TTNN/Pipelines/TTNNPipelines.h
  include/ttmlir/Dialect/TTNN/Utils/Conv2dConfigParams.h
  include/ttmlir/OpModel/TTNN/TTNNOpModel.h
  include/ttmlir/Target/TTNN/operations/conv.fbs
  include/ttmlir/Target/Utils/MLIRToFlatbuffer.h
  lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
  lib/Dialect/TTNN/Analysis/Conv2dConfigSearchSpace.cpp
  lib/Dialect/TTNN/Analysis/LegalOpConfigAnalysis.cpp
  lib/Dialect/TTNN/IR/TTNNOpsAttrs.cpp
  lib/Dialect/TTNN/Transforms/TTNNFusing.cpp
  lib/Dialect/TTNN/Utils/Conv2dConfigParams.cpp
  lib/Dialect/TTNN/Utils/PassOverrides.cpp
  lib/OpModel/TTNN/Conversion.cpp
  lib/OpModel/TTNN/TTNNOpModel.cpp
  lib/Target/TTKernel/TTKernelToCpp.cpp
  python/OptimizerOverrides.cpp
  python/TTNNModule.cpp
  runtime/lib/ttnn/operations/eltwise/unary/unary.cpp
  runtime/lib/ttnn/operations/utils/utils.cpp
  runtime/test/ttnn/dylib.cpp
  test/ttmlir/Dialect/TTNN/fusing/conv2d_activation_fusing.mlir
  test/ttmlir/Dialect/TTNN/fusing/conv2d_activation_fusing_ttnn.mlir
  test/ttmlir/Dialect/TTNN/fusing/resnet_pattern_fusing.mlir
  test/ttmlir/Dialect/TTNN/optimizer/conv2d_config_override.mlir
  test/ttmlir/EmitC/TTNN/conv/conv2d_conv2dconfig.mlir
  test/ttmlir/Silicon/TTNN/n150/fusing/resnet_pattern_fusing.mlir
  test/ttmlir/Silicon/TTNN/n150/optimizer/resnet50_fused_single_layer.mlir
  test/ttmlir/Silicon/TTNN/n150/perf/test_perf_conv2d_config.mlir
  test/ttmlir/Silicon/TTNN/n150/perf/test_perf_conv_transpose2d_with_conv2d_config.mlir
  test/unittests/OpModel/TTNN/Op/TestOpModelInterface.cpp
  test/unittests/Optimizer/TestConv2dConfigGenerator.cpp
  test/unittests/Optimizer/TestOptimizerOverrides.cpp
  third_party/CMakeLists.txt
  tools/explorer/tt_adapter/src/tt_adapter/main.py
  tools/explorer/tt_adapter/src/tt_adapter/mlir.py
Labels: uplift

#5030 Add callable initialization functions support to builder
  test/python/golden/test_ttir_ops.py
  tools/builder/base/builder.py
Labels: community
