Repository tenstorrent/tt-mlir, pull requests merged in 2025-05, with the labels that each got.

#3098 Uplift third_party/tt-metal to 3fbf1875cf87cdb4de7ecebc5b687c27ef49f13f 2025-04-29
  .github/workflows/build-and-test.yml
  docs/src/ci.md
  docs/src/ttrt.md
  include/ttmlir/Dialect/TTNN/Transforms/Workarounds/Decomposition/ConcatOpReshapeRewritePattern.h
  lib/Dialect/TTNN/Transforms/CMakeLists.txt
  lib/Dialect/TTNN/Transforms/Workarounds/Decomposition/ConcatOpReshapeRewritePattern.cpp
  lib/Dialect/TTNN/Transforms/Workarounds/TTNNWorkaroundsPatterns.cpp
  runtime/include/tt/runtime/types.h
  runtime/lib/ttnn/include/tt/runtime/ttnn/debug_apis.h
  runtime/lib/ttnn/runtime.cpp
  runtime/test/python/ttnn/multi_device/test_data_parallel.py
  runtime/test/python/ttnn/multi_device/test_input_deallocate.py
  runtime/test/python/ttnn/utils.py
  runtime/tools/python/test/test_run.py
  runtime/tools/python/ttrt/common/run.py
  runtime/tools/python/ttrt/runtime/module.cpp
  test/python/op_by_op_infra/test_mlir_module_executor.py
  test/python/op_by_op_infra/test_op_by_op_workflows.py
  test/ttmlir/Dialect/TTNN/Transforms/Workarounds/concat_workaround.mlir
  test/ttmlir/Silicon/StableHLO/n150/Binary/concat_op.mlir
  third_party/CMakeLists.txt
Labels: uplift

#3201 Mark ttkernel.get_compile_time_arg_val op as Pure
  include/ttmlir/Dialect/TTKernel/IR/TTKernelOps.td
Labels: community

#3197 Update ttmetal.enqueue_program_op verifier
  lib/Dialect/TTMetal/IR/TTMetalOps.cpp
Labels: community

#3188 Add workaround for concat op
  include/ttmlir/Dialect/TTNN/Transforms/Workarounds/Decomposition/ConcatOpReshapeRewritePattern.h
  lib/Dialect/TTNN/Transforms/Workarounds/Decomposition/ConcatOpReshapeRewritePattern.cpp
  test/ttmlir/Dialect/TTNN/Transforms/Workarounds/concat_workaround.mlir
  test/ttmlir/Silicon/StableHLO/n150/Binary/concat_op.mlir
Labels: workaround

#3055 Fix loc parsing in ttrt perf
  runtime/tools/python/ttrt/common/perf.py
  tools/explorer/tt_adapter/src/tt_adapter/mlir.py
Labels: ttrt

#3235 Uplift third_party/tt-metal to 1a9bf1ab81550daf2031b928e7152aabf1396260 2025-05-02
  include/ttmlir/OpModel/TTNN/SingletonDeviceContext.h
  lib/OpModel/TTNN/SingletonDeviceContext.cpp
  lib/OpModel/TTNN/TTNNOpModel.cpp
  runtime/lib/ttnn/runtime.cpp
  third_party/CMakeLists.txt
  tools/ttnn-standalone/CMakeLists.txt
Labels: uplift

#3257 Uplift third_party/tt-metal to 7e6553092db1c3d05e944e0b0bd99d26fcacc789 2025-05-08
  include/ttmlir/Conversion/TTNNToEmitC/EmitCConversion.h
  include/ttmlir/Dialect/TTNN/Transforms/Workarounds/Decomposition/ConcatOpReshapeRewritePattern.h
  lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
  lib/Conversion/TTNNToEmitC/TTNNToEmitCPass.cpp
  lib/Dialect/TTNN/Transforms/CMakeLists.txt
  lib/Dialect/TTNN/Transforms/Workarounds/Decomposition/ConcatOpReshapeRewritePattern.cpp
  lib/Dialect/TTNN/Transforms/Workarounds/TTNNWorkaroundsPatterns.cpp
  lib/OpModel/TTNN/SingletonDeviceContext.cpp
  runtime/lib/ttnn/utils/utils.cpp
  runtime/test/ttnn/dylib.cpp
  test/ttmlir/Dialect/TTNN/Transforms/Workarounds/concat_workaround.mlir
  test/ttmlir/EmitC/TTNN/tensor/repeat.mlir
  test/ttmlir/Silicon/StableHLO/n150/Binary/concat_op.mlir
  third_party/CMakeLists.txt
Labels: uplift

#3196 Add init_short and uninit ops for ttkernel tilize and untilize
  include/ttmlir/Dialect/TTKernel/IR/TTKernelOps.td
  lib/Conversion/TTKernelToEmitC/TTKernelToEmitC.cpp
  test/ttmlir/Conversion/TTKernelToEmitC/ttkernel.mlir
  test/ttmlir/Dialect/TTKernel/ops.mlir
Labels: community

#3273 Uplift third_party/tt-metal to c43020c7219c1ab2037c6b84a6e9923ca892e544 2025-05-09
  include/ttmlir/Conversion/TTNNToEmitC/EmitCConversion.h
  lib/OpModel/TTNN/Conversion.cpp
  runtime/lib/ttnn/utils/utils.cpp
  third_party/CMakeLists.txt
Labels: uplift

#3280 Fix tt-metal build dir path for tracy to work
  env/activate
  env/activate.fish
  runtime/tools/ttrt/setup.py
  third_party/CMakeLists.txt
  tools/ttnn-standalone/CMakeLists.txt
Labels: EmitC

#3311 Uplift third_party/tt-metal to 97e512f95c50f41767ccc2cd86e4ff824bb37e73 2025-05-12
  include/ttmlir/Dialect/TTNN/IR/TTNNOpsAttrs.td
  include/ttmlir/Dialect/TTNN/Pipelines/TTNNPipelines.h
  include/ttmlir/Dialect/TTNN/Utils/PassOverrides.h
  include/ttmlir/Target/TTNN/operations/conv.fbs
  include/ttmlir/Target/Utils/MLIRToFlatbuffer.h
  lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
  lib/Dialect/TTNN/Analysis/LegalLayoutAnalysis.cpp
  lib/Dialect/TTNN/IR/TTNNOpsAttrs.cpp
  lib/Dialect/TTNN/Utils/PassOverrides.cpp
  lib/OpModel/TTNN/Conversion.cpp
  lib/OpModel/TTNN/TTNNOpModel.cpp
  python/OptimizerOverrides.cpp
  python/TTNNModule.cpp
  runtime/lib/ttnn/operations/ccl/collective_permute.cpp
  runtime/lib/ttnn/operations/reduction/prod.cpp
  runtime/lib/ttnn/operations/utils/utils.cpp
  test/ttmlir/Dialect/TTNN/fusing/conv2d_activation_fusing_ttnn.mlir
  test/ttmlir/Dialect/TTNN/optimizer/conv2d_config_override.mlir
  test/ttmlir/Silicon/TTNN/n150/perf/test_perf_conv2d_config.mlir
  test/unittests/OpModel/TTNN/Op/TestOpModelInterface.cpp
  test/unittests/Optimizer/TestOptimizerOverrides.cpp
  third_party/CMakeLists.txt
  tools/explorer/tt_adapter/src/tt_adapter/main.py
  tools/explorer/tt_adapter/src/tt_adapter/mlir.py
Labels: uplift

#3332 Uplift third_party/tt-metal to ccfdebb197663efa8b85cc5ec0d83f30c174e0c9 2025-05-13
  runtime/include/tt/runtime/detail/ttnn/ttnn.h
  third_party/CMakeLists.txt
Labels: uplift

#3337 Export TTMLIRTTKernelToEmitC and MLIRTTTransforms
  cmake/modules/CMakeLists.txt
Labels: community

#3346 Uplift third_party/tt-metal to 3d4cffba4c2cfd72d8dda8f20e37dd5f00aca0e0 2025-05-13
  third_party/CMakeLists.txt
  tools/ttnn-standalone/CMakeLists.txt
Labels: uplift

#3359 Uplift third_party/tt-metal to 6f8b06c566a627fa06117852643175e1f9298c0a 2025-05-14
  third_party/CMakeLists.txt
Labels: uplift

#3382 Uplift third_party/tt-metal to 1a58dca1c570bc38bdef6b728b692ee4e8c34a55 2025-05-15
  lib/Dialect/TTNN/Analysis/LegalLayoutAnalysis.cpp
  lib/OpModel/TTNN/TTNNOpModel.cpp
  runtime/lib/ttnn/debug/debug_apis.cpp
  runtime/lib/ttnn/operations/ccl/collective_permute.cpp
  runtime/lib/ttnn/operations/eltwise/binary/binary_composite.cpp
  runtime/lib/ttnn/operations/kv_cache/update_cache.cpp
  runtime/lib/ttnn/operations/utils/utils.cpp
  runtime/lib/ttnn/runtime.cpp
  runtime/lib/ttnn/types/types.cpp
  runtime/lib/ttnn/utils/utils.cpp
  runtime/test/ttnn/dylib.cpp
  third_party/CMakeLists.txt
  tools/ttnn-standalone/CMakeLists.txt
  tools/ttnn-standalone/ttnn-precompiled.hpp
Labels: uplift

#3402 Uplift third_party/tt-metal to 0176b3bea0d4d4f0d296d73870e545a69c48a551 2025-05-16
  third_party/CMakeLists.txt
  tools/ttnn-standalone/CMakeLists.txt
Labels: uplift

#3430 Uplift third_party/tt-metal to 7ff86ba507e61e5b6cb9fd267030c4514a5223d1 2025-05-20
  third_party/CMakeLists.txt
Labels: uplift

#3487 Uplift third_party/tt-metal to f025854dea69b6b62c8b1ce0075917daffce6898 2025-05-21
  include/ttmlir/OpModel/TTNN/MetalHeaders.h
  runtime/include/tt/runtime/detail/ttnn/ttnn.h
  runtime/lib/ttnn/operations/eltwise/unary/unary.cpp
  runtime/test/python/ttnn/multi_device/test_input_deallocate.py
  third_party/CMakeLists.txt
  tools/ttnn-standalone/ttnn-precompiled.hpp
Labels: uplift

#3541 Fix hyper link in docs
  docs/src/getting-started.md
Labels: community

#3566 Uplift third_party/tt-metal to 992b7feaff4f8d05445969fe9c0070e89e53c0d1 2025-05-27
  include/ttmlir/Dialect/TTNN/IR/TTNNOpsEnums.td
  include/ttmlir/Target/TTNN/operations/eltwise.fbs
  include/ttmlir/Target/Utils/MLIRToFlatbuffer.h
  runtime/lib/ttnn/operations/utils/utils.cpp
  third_party/CMakeLists.txt
Labels: uplift

#3579 Uplift third_party/tt-metal to 17c897f7c80034e6fe46a416f309138785b765ff 2025-05-28
  lib/OpModel/TTNN/Conversion.cpp
  runtime/lib/ttnn/operations/conv/conv2d.cpp
  test/ttmlir/EmitC/TTNN/conv/conv2d_bf16.mlir
  test/ttmlir/EmitC/TTNN/conv/conv2d_f32.mlir
  test/ttmlir/EmitC/TTNN/conv/depthwise_conv2d.mlir
  test/ttmlir/EmitC/TTNN/conv/depthwise_separable_conv2d.mlir
  test/ttmlir/EmitC/TTNN/conv/dilated_conv2d.mlir
  test/ttmlir/EmitC/TTNN/conv/grouped_conv2d.mlir
  test/ttmlir/EmitC/TTNN/models/resnet.mlir
  third_party/CMakeLists.txt
Labels: uplift
