Repository tenstorrent/tt-mlir, pull requests merged in 2025-07, with the labels that each got.

#4000 Add mising dialect dependencies for `TTCoreRegisterDevicePass`
  include/ttmlir/Dialect/TTCore/Transforms/Passes.td
  lib/Dialect/TTCore/Transforms/TTCoreRegisterDevice.cpp
Labels: community

#4029 Uplift third_party/tt-metal to cf17101cb79329ee9369b2ab3075ef8a22c00008 2025-07-08
  include/ttmlir/Conversion/TTNNToEmitC/EmitCConversion.h
  include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
  include/ttmlir/Dialect/TTNN/IR/TTNNTraits.h
  include/ttmlir/Target/TTNN/operations/conv.fbs
  lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
  lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
  lib/Dialect/TTNN/Transforms/TTNNPrepareConv2dWeights.cpp
  lib/OpModel/TTNN/Conversion.cpp
  lib/OpModel/TTNN/TTNNOpModel.cpp
  lib/Target/TTNN/TTNNToFlatbuffer.cpp
  runtime/include/tt/runtime/detail/ttnn/ttnn.h
  runtime/include/tt/runtime/detail/ttnn/utils.h
  runtime/include/tt/runtime/runtime.h
  runtime/lib/runtime.cpp
  runtime/lib/ttnn/operations/ccl/collective_permute.cpp
  runtime/lib/ttnn/operations/conv/conv2d.cpp
  runtime/lib/ttnn/operations/conv/conv_transpose2d.cpp
  runtime/lib/ttnn/operations/conv/prepare_conv2d_weights.cpp
  runtime/lib/ttnn/operations/moreh/moreh_cumsum.cpp
  runtime/lib/ttnn/operations/utils/utils.cpp
  runtime/lib/ttnn/runtime.cpp
  runtime/lib/ttnn/utils/utils.cpp
  runtime/python/runtime/runtime.cpp
  test/ttmlir/Dialect/TTNN/Transforms/Workarounds/conv2d_workaround.mlir
  test/ttmlir/Dialect/TTNN/conv/conv2d/conv2d_tests_negative.mlir
  test/ttmlir/Dialect/TTNN/conv/prepare_conv2d_weights/prepare_conv2d_weights_negative.mlir
  test/ttmlir/Dialect/TTNN/fusing/conv2d_activation_fusing_ttnn.mlir
  test/ttmlir/EmitC/TTNN/conv/conv2d_conv2dconfig.mlir
  test/ttmlir/EmitC/TTNN/conv/conv2d_with_prepare_conv2d_weights.mlir
  test/ttmlir/EmitC/TTNN/conv/prepare_conv2d_weights.mlir
  test/ttmlir/EmitC/TTNN/conv/prepare_conv2d_weights_asymmetric_padding.mlir
  test/ttmlir/Silicon/TTNN/n150/conv/prepare_conv2d_weights/simple_prepare_conv2d_weights.mlir
  test/ttmlir/Silicon/TTNN/n150/perf/test_perf_conv2d_config.mlir
  test/ttmlir/Silicon/TTNN/n150/perf/test_perf_conv2d_device_compute_kernel_config.mlir
  test/ttmlir/Silicon/TTNN/n150/perf/test_perf_conv_transpose2d_with_conv2d_config.mlir
  test/unittests/OpModel/TTNN/Op/TestOpModelInterface.cpp
  third_party/CMakeLists.txt
Labels: uplift

#4059 Used shared last updated action from tt-forge
  .github/workflows/issue-last-updated.yml
Labels: CI / Infra

#4072 Uplift third_party/tt-metal to 5119c0b25a2d09a3116fb0427a39e4146d8990d6 2025-07-15
  third_party/CMakeLists.txt
  tools/ttnn-standalone/CMakeLists.txt
Labels: uplift

#4026 Support cpu fallback max reduce op
  test/python/golden/test_ttir_ops.py
  tools/ttir-builder/ops.py
Labels: bounty

#4086 Uplift third_party/tt-metal to 7cd5738b35e8dc4862ef13a21468cb98264dbef6 2025-07-16
  lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
  runtime/include/tt/runtime/detail/ttnn/ttnn.h
  runtime/lib/ttnn/operations/reduction/sort.cpp
  third_party/CMakeLists.txt
  tools/ttnn-standalone/ttnn-precompiled.hpp
Labels: uplift

#4087 Uplift model-explorer to 99da5ea9334119ad6bcaaf181b5c64c9504ccf82 2025-07-18
  tools/explorer/CMakeLists.txt
Labels: uplift

#4119 Uplift third_party/tt-metal to 81412069f02b01a483cc0fb29fec5c9bf28ac1ab 2025-07-18
  docs/src/ttir-builder/ttir-builder.md
  include/ttmlir/Dialect/TTKernel/IR/TTKernelOps.td
  lib/Conversion/TTIRToTTKernel/TTIRToTTKernel.cpp
  lib/Dialect/TTKernel/IR/TTKernelOps.cpp
  test/ttmlir/Conversion/TTKernelToEmitC/ttkernel.mlir
  test/ttmlir/Translate/TTKernel/ttkernel_compute.mlir
  third_party/CMakeLists.txt
Labels: uplift

#4153 Uplift model-explorer to a333e83c65fe8dc86f340c606c49ee262420b4ec 2025-07-22
  tools/explorer/CMakeLists.txt
Labels: uplift

#4144 Remove arg attrs from FuncOp when going to EmitC
  lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
  lib/Conversion/TTNNToEmitC/TTNNToEmitCPass.cpp
  test/ttmlir/EmitC/TTNN/other/const-eval-device.mlir
  test/ttmlir/EmitC/TTNN/other/const-eval.mlir
Labels: EmitC

#4108 Update EmitC test docs: single test
  docs/src/emitc-testing.md
  docs/src/ttrt.md
Labels: EmitC

#4247 fix embeddingOp Constraint API to handle nullptr output layout
  lib/OpModel/TTNN/TTNNOpModel.cpp
  test/unittests/OpModel/TTNN/Op/TestOpModelInterface.cpp
Labels: ttnn constraints

#4285 Uplift model-explorer to 7dbec56d8fdeaa62c9761db7a25527d35fa8208b 2025-07-31
  tools/explorer/CMakeLists.txt
Labels: uplift

#4151 Refactor TTNN to EmitPy conversion using EmitPyTTNNEmitter
  .github/CODEOWNERS
  include/ttmlir/Conversion/TTNNToEmitPy/EmitPyConversion.h
  include/ttmlir/Dialect/EmitPy/IR/EmitPyOps.td
  include/ttmlir/Dialect/EmitPy/IR/EmitPyTypes.td
  lib/Conversion/TTNNToEmitPy/TTNNToEmitPy.cpp
  lib/Target/Python/TranslateToPython.cpp
  test/ttmlir/Dialect/EmitPy/ttir_to_emitpy_pipeline_sanity.mlir
Labels: EmitPy
